Repository nextcloud/data_request, pull requests merged in 2018-05, with the labels that each got.

#2 Add transifex config
  .tx/config
Labels: 3. to review

#1 initial feature set
  .drone.yml
  .scrutinizer.yml
  COPYING
  Makefile
  appinfo/info.xml
  appinfo/routes.php
  css/style.scss
  img/app.svg
  js/app.js
  js/init.js
  lib/Controller/DataRequestController.php
  lib/Exceptions/HintedRuntime.php
  lib/Services/Request.php
  lib/Settings/Personal.php
  templates/Settings/personal.php
Labels: 3. to review, enhancement

#4 add screenshots
  appinfo/info.xml
  screenshots/personal-settings.png
  screenshots/settings-close-up.png
Labels: 3. to review

#5 ignore screenshot folder for build
  krankerl.toml
Labels: 3. to review

#6 fix screenshot urls :-/
  appinfo/info.xml
Labels: 3. to review, bug

#13 always send with default email address
  .gitignore
  lib/Services/Request.php
Labels: 3. to review, bug
