Repository nextcloud/data_request, pull requests merged in 2022-11, with the labels that each got.

#89 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#84 Updating phpunit-pgsql.yml workflow from template
  .github/workflows/phpunit-pgsql.yml
Labels: dependencies

#90 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#87 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#86 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#85 Updating phpunit-sqlite.yml workflow from template
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies

#77 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#83 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#82 Updating phpunit-oci.yml workflow from template
  .github/workflows/phpunit-oci.yml
Labels: dependencies

#81 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#80 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#71 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#91 add website info; add return type hints
  appinfo/info.xml
  lib/Settings/Personal.php
Labels: 4. to release, backport-request
