Repository nextcloud/data_request, pull requests merged in 2023-05, with the labels that each got.

#117 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#119 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#120 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#121 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#123 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#122 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#124 Release: v1.14.0
  CHANGELOG.md
Labels: 3. to review

#127 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#128 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#129 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated
