Repository nextcloud/data_request, pull requests merged in 2023-12, with the labels that each got.

#162 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#163 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#188 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#186 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#192 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#191 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#189 [stable27] Fix nextcloud OCP updates
  composer.json
  composer.lock
Labels: 3. to review

#195 chore: update workflows from templates
  .github/workflows/psalm.yml
Labels: 3. to review, dependencies, automated

#196 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated
