Repository nextcloud/data_request, pull requests merged in 2024-10, with the labels that each got.

#299 Add reuse compliance
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/reuse.yml
  .gitignore
  .nextcloudignore
  .php-cs-fixer.dist.php
  AUTHORS.md
  CHANGELOG.md
  LICENSES/AGPL-3.0-or-later.txt
  LICENSES/Apache-2.0.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  Makefile
  README.md
  REUSE.toml
  appinfo/info.xml
  appinfo/routes.php
  css/style.scss
  cypress.config.mjs
  cypress/e2e/app.cy.js
  cypress/support/addGetter.js
  cypress/support/commands.js
  cypress/support/e2e.js
  img/app.svg
  js/app.js
  js/init.js
  krankerl.toml
  lib/Controller/DataRequestController.php
  lib/Exceptions/HintedRuntime.php
  lib/Services/Request.php
  lib/Settings/Personal.php
  screenshots/personal-settings.png.license
  screenshots/settings-close-up.png.license
  templates/Settings/personal.php
  tests/bootstrap.php
  tests/phpunit.xml
  tests/unit/Controller/DataRequestControllerTest.php
  tests/unit/Services/RequestTest.php
Labels: 3. to review, technical debt

#298 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#300 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#301 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#288 chore(CI): Updating cypress.yml workflow from template
  .github/workflows/cypress.yml
Labels: dependencies

#305 fix(deps): use psr-log 3 compatible with latest ocp
  composer.lock
Labels: 3. to review, dependencies

#306 fix(deps): use psr-log compatible with latest ocp
  composer.lock
Labels: 3. to review, dependencies

#307 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#308 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#309 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#302 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
