Repository nextcloud/data_request, pull requests merged in 2024-09, with the labels that each got.

#273 chore(CI): Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#252 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#261 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/cypress.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#272 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#275 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#258 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#274 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#286 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#287 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#292 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#293 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#294 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#295 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#297 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
