Repository nextcloud/data_request, pull requests merged in 2024-01, with the labels that each got.

#198 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#200 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#199 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#201 enh(ci): autoapprove and automerge ocp updates
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
Labels: 3. to review

#197 test(cy): initial cypress tests
  .github/workflows/cypress.yml
  .gitignore
  Makefile
  README.md
  cypress.config.mjs
  cypress/e2e/app.cy.js
  cypress/support/addGetter.js
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: 3. to review, enhancement

#202 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#203 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#207 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#208 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#211 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
